services:
  - type: web
    name: product-importer-web
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        value: redis://red-d4c463bipnbc73971ao0:6379
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com

  - type: worker
    name: product-importer-worker
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info --concurrency=4"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        value: redis://red-d4c463bipnbc73971ao0:6379
      - key: SECRET_KEY
        sync: false

databases:
  - name: product-importer-db
    plan: free
    databaseName: product_importer
    user: product_importer
